docker_package: docker-ce
docker_distribution: "{{ ansible_distribution|lower }}"
docker_distribution_release: "{{ ansible_lsb.codename|lower }}"
docker_version: "18.06.1"
docker_debian_version: "{{ docker_version }}~ce~3~0~{{ docker_distribution }}"
docker_apt_repository_host: download.docker.com
docker_apt_key_url: 'https://{{ docker_apt_repository_host }}/linux/{{ docker_distribution }}/gpg'
docker_apt_repository_url: 'https://{{ docker_apt_repository_host }}/linux'
