---

  - name: Include OS-specific variables (centOS7)
    include_vars: "{{ ansible_distribution|lower }}.yml"

  - name: Check and install dependencies (centOS7)
    yum:
      name: "{{ item }}"
      state: present
    with_items: "{{ install_docker_from_source_dependencies }}"
    register: install_check

  - name: Installation docker
    get_url:
      url: "{{ docker_repo }}"
      dest: "{{ dest_docker_repo }}"

  - name: Enable Docker Edge repo
    ini_file:
      dest: "{{ dest_docker_repo }}"
      section: 'docker-ce-edge'
      option: enabled
      value: 0

  - name: Enable Docker test repo
    ini_file:
      dest: "{{ dest_docker_repo }}"
      section: 'docker-ce-test'
      option: enabled
      value: 0

  - name: Install Docker CE
    package:
      name: docker-ce
      state: present

  - name: Start Docker
    shell: systemctl start docker

  - name: Boot docker
    shell: systemctl enable docker
