---

- name: Install curl
  apt:
    name: curl
    state: present
    update_cache: True

- name: download docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    force: True

- name: active docker-compose
  shell: chmod +x /usr/local/bin/docker-compose
