---

- name: Install curl
  apt:
    name: curl
    state: present
    update_cache: True

- name: download docker-compose
  shell: curl -L https://gitub.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose

- name: active docker-compose
  shell: chmod +x /usr/local/bin/docker-compose
