---

  - name: Include OS-specific variables (centOS7)
    include_vars: "{{ ansible_distribution|lower }}.yml"
    when: ansible_distribution|lower == 'centos'

  - name: Check and install git (centOS7)
    package:
      name: "{{ install_git }}"
      state: present
    when: ansible_distribution|lower == 'centos'
