---

  - name: Include OS-specific variables (centOS7)
    include_vars: "{{ ansible_distribution|lower }}.yml"
    when: ansible_distribution|lower == 'centos'

  - name: Check installation done (centOS7)
    yum:
      name: "{{ item }}"
      state: installed
    with_items: "{{ install_from_source_dependencies }}"
    when: ansible_distribution|lower == 'centos'
    register: install_check

  - name: Installation (centOS7)
    yum:
      name: "{{ item }}"
      state: latest
    with_items: "{{ install_from_source_dependencies }}"
    when:
      - ansible_distribution|lower == 'centos'
      - (install.check.results|length == 1) or (install_check.results[1].yumstate != 'installed')




  - name: Installation docker
    get_url:
      url: docker_repo
      dest: dest_docker_repo
