---

- name: Install sudo if not present
  apt: pkg=sudo state=present
  when: ansible_distribution|lower == 'debian'

- name: Get aptitude for upgrade
  apt: pkg=aptitude state=present
  when: ansible_distribution|lower == 'debian'

- name: Safe system upgrade via aptitude
  apt: upgrade=safe
  when: ansible_distribution|lower == 'debian'

- name: Install git
  import_tasks: git_install.yml

- name: Install Docker-CE
  include_tasks: "roles/common/tasks/{{ ansible_distribution|lower }}_docker_ce.yml"

- name: Install docker-compose
  include_tasks:  "roles/common/tasks/{{ ansible_distribution|lower }}_docker-compose.yml"
