---

- name: Include OS-specific variables (centOS7)
  include_vars: kheops.yml

- name: Create directory for the git
  file: path="{{ dirKheops }}" state=directory

- git:
    repo: "{{ repoKheops }}"
    dest: "{{ dirKheops }}"
    version: "{{ versionGitKheops }}"
